### ISSUE TITLE
Things don't work on windows

### ISSUE THREAD

**Issue by abrelsfo** [dawsonbotsford/sist#1]
shell isn't working on windows ~~and it's adding in ruby and go even though they aren't in the repository~~.

### shell
`uname`: `error, return code 1`
`echo $SHELL`: $SHELL
`echo $TERM`: $TERM
`echo $TERM_PROGRAM`: $TERM_PROGRAM
`a`: `error, return code 1`

### node
`npm -v`: 3.7.5
`node --version`: v5.7.0

### ruby
`ruby --version`: `error, return code 1`

### go
`go --version`: `error, return code 1`

Time created: Fri Mar 04 2016 08:15:42 GMT-0500 (Eastern Standard Time)

<br>

## Added 3-04:
[sist](https://github.com/dawsonbotsford/sist) output:

### OS
Microsoft Windows 7 Enterprise
Windows_NT
x64

### node
`npm -v`: 3.7.5
`node --version`: v5.7.0

Time created: Fri Mar 04 2016 16:07:02 GMT-0500 (Eastern Standard Time)

### Description
Command: sist node

Always adds OS. The OS Name is only for windows but the other two should work for mac, linux, and SunOS

**Comment by dawsonbotsford** [comment]
ruby and go are supposed to be added in since you ran `sist` without any additional arguments. Per version `0.1.0` if you wanted just node and shell you would run `sist shell node`.

Your first point is very valid though. I've never used any of those shell commands on windows.

1. Is there a different command instead of `echo` on windows?

2. What is the output of `echo $SHELL`/how do you print a globabl shell variable like that in Windows?

**Comment by dawsonbotsford** [comment]
Closed with 68cc66d
